/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleForm: typeof import('./src/components/admin/articles/ArticleForm.vue')['default']
    CreateArticleDialog: typeof import('./src/components/admin/articles/CreateArticleDialog.vue')['default']
    DeleteArticleDialog: typeof import('./src/components/admin/articles/DeleteArticleDialog.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/auth/ForgotPasswordForm.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    NewPasswordForm: typeof import('./src/components/auth/NewPasswordForm.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RegisterOTP: typeof import('./src/components/auth/RegisterOTP.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
