export enum OrderStatus {
    NEW = 'NEW',
    IN_PROGRESS = 'IN_PROGRESS',
    PENDING_PAYMENT = 'PENDING_PAYMENT',
    PAID = 'PAID',
    TO_SHIP = 'TO_SHIP',
    SHIPPED = 'SHIPPED',
    DONE = 'DONE',
    CANCELLED = 'CANCELLED',
}

export enum IllustrationStatus {
    PENDING = 'PENDING',
    DEPOSIT_PENDING = 'DEPOSIT_PENDING',
    DEPOSIT_PAID = 'DEPOSIT_PAID',
    IN_PROGRESS = 'IN_PROGRESS',
    CLIENT_REVIEW = 'CLIENT_REVIEW',
    PAYMENT_PENDING = 'PAYMENT_PENDING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}
